version: "3"

env:
  TAG_NAME: registry.aquilla.dev/productsyndicate/ttl-agent
  REPO: registry.aquilla.dev

tasks:
  bump:
    desc: Bump the version
    cmds:
      - echo $(cat VERSION) | awk -F. '/[0-9]+\./{$NF++;print}' OFS=. > tmp && mv -f tmp VERSION #replacement for bumpversion
  build:
    desc: Build the docker image
    cmds:
      - docker buildx build --platform=linux/amd64 -t $TAG_NAME . --load
      - docker tag ${TAG_NAME}:latest ${TAG_NAME}:latest
      - docker tag ${TAG_NAME}:latest ${TAG_NAME}:$(cat VERSION)
  push:
    desc: Push docker image to private repo
    cmds:
      - docker login $REPO
      - docker push ${TAG_NAME}:$(cat VERSION)
      - docker push ${TAG_NAME}:latest